// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/contracts/sso.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OIDCModuleConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*ProviderConfig      `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OIDCModuleConfig) Reset() {
	*x = OIDCModuleConfig{}
	mi := &file_internal_contracts_sso_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OIDCModuleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OIDCModuleConfig) ProtoMessage() {}

func (x *OIDCModuleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_sso_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OIDCModuleConfig.ProtoReflect.Descriptor instead.
func (*OIDCModuleConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_sso_proto_rawDescGZIP(), []int{0}
}

func (x *OIDCModuleConfig) GetProviders() []*ProviderConfig {
	if x != nil {
		return x.Providers
	}
	return nil
}

type ProviderConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Issuer        string                 `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,5,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	RedirectUrl   string                 `protobuf:"bytes,6,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	TenantId      string                 `protobuf:"bytes,7,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Domain        string                 `protobuf:"bytes,8,opt,name=domain,proto3" json:"domain,omitempty"`
	AuthServerId  string                 `protobuf:"bytes,9,opt,name=auth_server_id,json=authServerId,proto3" json:"auth_server_id,omitempty"`
	Scopes        []string               `protobuf:"bytes,10,rep,name=scopes,proto3" json:"scopes,omitempty"`
	ClaimMapping  *ClaimMapping          `protobuf:"bytes,11,opt,name=claim_mapping,json=claimMapping,proto3" json:"claim_mapping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderConfig) Reset() {
	*x = ProviderConfig{}
	mi := &file_internal_contracts_sso_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderConfig) ProtoMessage() {}

func (x *ProviderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_sso_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderConfig.ProtoReflect.Descriptor instead.
func (*ProviderConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_sso_proto_rawDescGZIP(), []int{1}
}

func (x *ProviderConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProviderConfig) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *ProviderConfig) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ProviderConfig) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *ProviderConfig) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

func (x *ProviderConfig) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ProviderConfig) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ProviderConfig) GetAuthServerId() string {
	if x != nil {
		return x.AuthServerId
	}
	return ""
}

func (x *ProviderConfig) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *ProviderConfig) GetClaimMapping() *ClaimMapping {
	if x != nil {
		return x.ClaimMapping
	}
	return nil
}

type ClaimMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         string                 `protobuf:"bytes,1,opt,name=roles,proto3" json:"roles,omitempty"`
	Groups        string                 `protobuf:"bytes,2,opt,name=groups,proto3" json:"groups,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimMapping) Reset() {
	*x = ClaimMapping{}
	mi := &file_internal_contracts_sso_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimMapping) ProtoMessage() {}

func (x *ClaimMapping) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_sso_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimMapping.ProtoReflect.Descriptor instead.
func (*ClaimMapping) Descriptor() ([]byte, []int) {
	return file_internal_contracts_sso_proto_rawDescGZIP(), []int{2}
}

func (x *ClaimMapping) GetRoles() string {
	if x != nil {
		return x.Roles
	}
	return ""
}

func (x *ClaimMapping) GetGroups() string {
	if x != nil {
		return x.Groups
	}
	return ""
}

func (x *ClaimMapping) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ClaimMapping) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ValidateTokenConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenConfig) Reset() {
	*x = ValidateTokenConfig{}
	mi := &file_internal_contracts_sso_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenConfig) ProtoMessage() {}

func (x *ValidateTokenConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_sso_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenConfig.ProtoReflect.Descriptor instead.
func (*ValidateTokenConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_sso_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateTokenConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type ValidateTokenInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Authorization string                 `protobuf:"bytes,2,opt,name=authorization,proto3" json:"authorization,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenInput) Reset() {
	*x = ValidateTokenInput{}
	mi := &file_internal_contracts_sso_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenInput) ProtoMessage() {}

func (x *ValidateTokenInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_sso_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenInput.ProtoReflect.Descriptor instead.
func (*ValidateTokenInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_sso_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateTokenInput) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ValidateTokenInput) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

func (x *ValidateTokenInput) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type ValidateTokenOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Roles         []string               `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	Groups        []string               `protobuf:"bytes,6,rep,name=groups,proto3" json:"groups,omitempty"`
	Provider      string                 `protobuf:"bytes,7,opt,name=provider,proto3" json:"provider,omitempty"`
	Claims        *structpb.Struct       `protobuf:"bytes,8,opt,name=claims,proto3" json:"claims,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Error         string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenOutput) Reset() {
	*x = ValidateTokenOutput{}
	mi := &file_internal_contracts_sso_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenOutput) ProtoMessage() {}

func (x *ValidateTokenOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_sso_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenOutput.ProtoReflect.Descriptor instead.
func (*ValidateTokenOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_sso_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateTokenOutput) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenOutput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateTokenOutput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ValidateTokenOutput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ValidateTokenOutput) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ValidateTokenOutput) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ValidateTokenOutput) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ValidateTokenOutput) GetClaims() *structpb.Struct {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *ValidateTokenOutput) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *ValidateTokenOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UserInfoConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoConfig) Reset() {
	*x = UserInfoConfig{}
	mi := &file_internal_contracts_sso_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoConfig) ProtoMessage() {}

func (x *UserInfoConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_sso_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoConfig.ProtoReflect.Descriptor instead.
func (*UserInfoConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_sso_proto_rawDescGZIP(), []int{6}
}

func (x *UserInfoConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type UserInfoInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoInput) Reset() {
	*x = UserInfoInput{}
	mi := &file_internal_contracts_sso_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoInput) ProtoMessage() {}

func (x *UserInfoInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_sso_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoInput.ProtoReflect.Descriptor instead.
func (*UserInfoInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_sso_proto_rawDescGZIP(), []int{7}
}

func (x *UserInfoInput) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *UserInfoInput) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type UserInfoOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Sub           string                 `protobuf:"bytes,2,opt,name=sub,proto3" json:"sub,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Profile       string                 `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	Claims        *structpb.Struct       `protobuf:"bytes,5,opt,name=claims,proto3" json:"claims,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoOutput) Reset() {
	*x = UserInfoOutput{}
	mi := &file_internal_contracts_sso_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoOutput) ProtoMessage() {}

func (x *UserInfoOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_sso_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoOutput.ProtoReflect.Descriptor instead.
func (*UserInfoOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_sso_proto_rawDescGZIP(), []int{8}
}

func (x *UserInfoOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UserInfoOutput) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *UserInfoOutput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfoOutput) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *UserInfoOutput) GetClaims() *structpb.Struct {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *UserInfoOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TokenExchangeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenExchangeConfig) Reset() {
	*x = TokenExchangeConfig{}
	mi := &file_internal_contracts_sso_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenExchangeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenExchangeConfig) ProtoMessage() {}

func (x *TokenExchangeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_sso_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenExchangeConfig.ProtoReflect.Descriptor instead.
func (*TokenExchangeConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_sso_proto_rawDescGZIP(), []int{9}
}

func (x *TokenExchangeConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type TokenExchangeInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenExchangeInput) Reset() {
	*x = TokenExchangeInput{}
	mi := &file_internal_contracts_sso_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenExchangeInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenExchangeInput) ProtoMessage() {}

func (x *TokenExchangeInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_sso_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenExchangeInput.ProtoReflect.Descriptor instead.
func (*TokenExchangeInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_sso_proto_rawDescGZIP(), []int{10}
}

func (x *TokenExchangeInput) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TokenExchangeInput) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type TokenExchangeOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	IdToken       string                 `protobuf:"bytes,4,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,5,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,6,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenExchangeOutput) Reset() {
	*x = TokenExchangeOutput{}
	mi := &file_internal_contracts_sso_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenExchangeOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenExchangeOutput) ProtoMessage() {}

func (x *TokenExchangeOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_sso_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenExchangeOutput.ProtoReflect.Descriptor instead.
func (*TokenExchangeOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_sso_proto_rawDescGZIP(), []int{11}
}

func (x *TokenExchangeOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TokenExchangeOutput) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenExchangeOutput) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenExchangeOutput) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

func (x *TokenExchangeOutput) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenExchangeOutput) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *TokenExchangeOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RefreshTokenConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenConfig) Reset() {
	*x = RefreshTokenConfig{}
	mi := &file_internal_contracts_sso_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenConfig) ProtoMessage() {}

func (x *RefreshTokenConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_sso_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenConfig.ProtoReflect.Descriptor instead.
func (*RefreshTokenConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_sso_proto_rawDescGZIP(), []int{12}
}

func (x *RefreshTokenConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type RefreshTokenInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenInput) Reset() {
	*x = RefreshTokenInput{}
	mi := &file_internal_contracts_sso_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenInput) ProtoMessage() {}

func (x *RefreshTokenInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_sso_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenInput.ProtoReflect.Descriptor instead.
func (*RefreshTokenInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_sso_proto_rawDescGZIP(), []int{13}
}

func (x *RefreshTokenInput) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenInput) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type RefreshTokenOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenOutput) Reset() {
	*x = RefreshTokenOutput{}
	mi := &file_internal_contracts_sso_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenOutput) ProtoMessage() {}

func (x *RefreshTokenOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_sso_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenOutput.ProtoReflect.Descriptor instead.
func (*RefreshTokenOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_sso_proto_rawDescGZIP(), []int{14}
}

func (x *RefreshTokenOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefreshTokenOutput) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenOutput) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenOutput) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *RefreshTokenOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_contracts_sso_proto protoreflect.FileDescriptor

const file_internal_contracts_sso_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/contracts/sso.proto\x12\x17workflow.plugins.sso.v1\x1a\x1cgoogle/protobuf/struct.proto\"Y\n" +
	"\x10OIDCModuleConfig\x12E\n" +
	"\tproviders\x18\x01 \x03(\v2'.workflow.plugins.sso.v1.ProviderConfigR\tproviders\"\xf4\x02\n" +
	"\x0eProviderConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06issuer\x18\x03 \x01(\tR\x06issuer\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x05 \x01(\tR\fclientSecret\x12!\n" +
	"\fredirect_url\x18\x06 \x01(\tR\vredirectUrl\x12\x1b\n" +
	"\ttenant_id\x18\a \x01(\tR\btenantId\x12\x16\n" +
	"\x06domain\x18\b \x01(\tR\x06domain\x12$\n" +
	"\x0eauth_server_id\x18\t \x01(\tR\fauthServerId\x12\x16\n" +
	"\x06scopes\x18\n" +
	" \x03(\tR\x06scopes\x12J\n" +
	"\rclaim_mapping\x18\v \x01(\v2%.workflow.plugins.sso.v1.ClaimMappingR\fclaimMapping\"f\n" +
	"\fClaimMapping\x12\x14\n" +
	"\x05roles\x18\x01 \x01(\tR\x05roles\x12\x16\n" +
	"\x06groups\x18\x02 \x01(\tR\x06groups\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"1\n" +
	"\x13ValidateTokenConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\"l\n" +
	"\x12ValidateTokenInput\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12$\n" +
	"\rauthorization\x18\x02 \x01(\tR\rauthorization\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\"\x9e\x02\n" +
	"\x13ValidateTokenOutput\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05roles\x18\x05 \x03(\tR\x05roles\x12\x16\n" +
	"\x06groups\x18\x06 \x03(\tR\x06groups\x12\x1a\n" +
	"\bprovider\x18\a \x01(\tR\bprovider\x12/\n" +
	"\x06claims\x18\b \x01(\v2\x17.google.protobuf.StructR\x06claims\x12\x1d\n" +
	"\n" +
	"expires_at\x18\t \x01(\tR\texpiresAt\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\",\n" +
	"\x0eUserInfoConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\"N\n" +
	"\rUserInfoInput\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\"\xb3\x01\n" +
	"\x0eUserInfoOutput\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03sub\x18\x02 \x01(\tR\x03sub\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x18\n" +
	"\aprofile\x18\x04 \x01(\tR\aprofile\x12/\n" +
	"\x06claims\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x06claims\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"1\n" +
	"\x13TokenExchangeConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\"D\n" +
	"\x12TokenExchangeInput\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\"\xe6\x01\n" +
	"\x13TokenExchangeOutput\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x19\n" +
	"\bid_token\x18\x04 \x01(\tR\aidToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x05 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x06 \x01(\x05R\texpiresIn\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"0\n" +
	"\x12RefreshTokenConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\"T\n" +
	"\x11RefreshTokenInput\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\"\xab\x01\n" +
	"\x12RefreshTokenOutput\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x05R\texpiresIn\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05errorB?Z=github.com/GoCodeAlone/workflow-plugin-sso/internal/contractsb\x06proto3"

var (
	file_internal_contracts_sso_proto_rawDescOnce sync.Once
	file_internal_contracts_sso_proto_rawDescData []byte
)

func file_internal_contracts_sso_proto_rawDescGZIP() []byte {
	file_internal_contracts_sso_proto_rawDescOnce.Do(func() {
		file_internal_contracts_sso_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_contracts_sso_proto_rawDesc), len(file_internal_contracts_sso_proto_rawDesc)))
	})
	return file_internal_contracts_sso_proto_rawDescData
}

var file_internal_contracts_sso_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_internal_contracts_sso_proto_goTypes = []any{
	(*OIDCModuleConfig)(nil),    // 0: workflow.plugins.sso.v1.OIDCModuleConfig
	(*ProviderConfig)(nil),      // 1: workflow.plugins.sso.v1.ProviderConfig
	(*ClaimMapping)(nil),        // 2: workflow.plugins.sso.v1.ClaimMapping
	(*ValidateTokenConfig)(nil), // 3: workflow.plugins.sso.v1.ValidateTokenConfig
	(*ValidateTokenInput)(nil),  // 4: workflow.plugins.sso.v1.ValidateTokenInput
	(*ValidateTokenOutput)(nil), // 5: workflow.plugins.sso.v1.ValidateTokenOutput
	(*UserInfoConfig)(nil),      // 6: workflow.plugins.sso.v1.UserInfoConfig
	(*UserInfoInput)(nil),       // 7: workflow.plugins.sso.v1.UserInfoInput
	(*UserInfoOutput)(nil),      // 8: workflow.plugins.sso.v1.UserInfoOutput
	(*TokenExchangeConfig)(nil), // 9: workflow.plugins.sso.v1.TokenExchangeConfig
	(*TokenExchangeInput)(nil),  // 10: workflow.plugins.sso.v1.TokenExchangeInput
	(*TokenExchangeOutput)(nil), // 11: workflow.plugins.sso.v1.TokenExchangeOutput
	(*RefreshTokenConfig)(nil),  // 12: workflow.plugins.sso.v1.RefreshTokenConfig
	(*RefreshTokenInput)(nil),   // 13: workflow.plugins.sso.v1.RefreshTokenInput
	(*RefreshTokenOutput)(nil),  // 14: workflow.plugins.sso.v1.RefreshTokenOutput
	(*structpb.Struct)(nil),     // 15: google.protobuf.Struct
}
var file_internal_contracts_sso_proto_depIdxs = []int32{
	1,  // 0: workflow.plugins.sso.v1.OIDCModuleConfig.providers:type_name -> workflow.plugins.sso.v1.ProviderConfig
	2,  // 1: workflow.plugins.sso.v1.ProviderConfig.claim_mapping:type_name -> workflow.plugins.sso.v1.ClaimMapping
	15, // 2: workflow.plugins.sso.v1.ValidateTokenOutput.claims:type_name -> google.protobuf.Struct
	15, // 3: workflow.plugins.sso.v1.UserInfoOutput.claims:type_name -> google.protobuf.Struct
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_internal_contracts_sso_proto_init() }
func file_internal_contracts_sso_proto_init() {
	if File_internal_contracts_sso_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_contracts_sso_proto_rawDesc), len(file_internal_contracts_sso_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_contracts_sso_proto_goTypes,
		DependencyIndexes: file_internal_contracts_sso_proto_depIdxs,
		MessageInfos:      file_internal_contracts_sso_proto_msgTypes,
	}.Build()
	File_internal_contracts_sso_proto = out.File
	file_internal_contracts_sso_proto_goTypes = nil
	file_internal_contracts_sso_proto_depIdxs = nil
}
